version: '3.1'
services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: abett
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - "3306:3306"

  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:3306

volumes:
  db_data: